school/school_management/order/urls.py
from . import views
from django.urls import path




urlpatterns = [
    path('place_order/',views.place_orders,name='place_order'),
    # path('<int:pk>/', views.person_update_view, name='person_change'),
    path('ajax_load_course/', views.load_course, name='ajax_load_course'),
      
]

school/school_management/school_management/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('Account.urls')),
    path('order/',include('order.urls')),
    path('myadmin/',include('superadmin.urls')),
    # path('department/',include('Department.urls')),
]
 

school/school_management/order/models.py
from django.db import models
from Account.models import Account,Materials
from Department.models import Course
from Department.models import Department


class Order(models.Model):

    purpose_types = (
        ('Enquiry', 'Enquiry'),
        ('place_order', 'place_order')
    )

    TYPES = (

        ('Male' , 'Male'),
        ( 'Woman' , 'Woman'),
    )


    name = models.CharField(max_length=255)
    email = models.CharField(max_length=255, unique=True)
    mobile =  models.CharField(max_length=10,null=True,blank=True)
    user =models.ForeignKey(Account,on_delete=models.CASCADE,null=True)
    date_of_birth =  models.DateField(null=True,blank=True)
    age = models.IntegerField(null=True)
    gender = models.CharField(max_length=10, choices=TYPES)
    address=models.TextField()
    course        = models.ForeignKey(Course,on_delete=models.CASCADE,null=True)
    purpose       = models.TextField(max_length=255, choices=purpose_types)
    materials     = models.ForeignKey(Materials,on_delete=models.CASCADE,null=True)
    department    = models.ForeignKey(Department,on_delete=models.CASCADE,null=True)
    
    def __str__(self):
        return self.name

school/school_management/order/forms.py
from django import forms
from .models import Order,Course


class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ['name','date_of_birth','mobile','email','address','age','gender','department','course','purpose','materials']
    

   

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['course'].queryset = Course.objects.none()

        if 'department' in self.data:
            try:
                department_id = int(self.data.get('department'))
                self.fields['course'].queryset = Course.objects.filter(department_id=department_id).all()
            except (ValueError, TypeError):
                pass  # invalid input from the client; ignore and fallback to empty City queryset
        # elif self.instance.pk:
        #     self.fields['course'].queryset = self.instance.department.course_set.order_by('name')

school/school_management/order/views.py
from django.shortcuts import render
from django.shortcuts import render,redirect
from .forms import OrderForm
from .models import Order
from .models import Course
from django.contrib.auth.decorators import login_required
from django .contrib import messages,auth
from django.http import JsonResponse
from django.shortcuts import render, redirect, get_object_or_404


@login_required(login_url='login')
def place_orders(request):
    
    form = OrderForm()
    if request.method == 'POST':
        form = OrderForm(request.POST)
        if form.is_valid():
            form.save()
            messages.error(request,'Order Confirmed') 
            return redirect('place_order')
        
        messages.error(request,'OrderNot Confirmed') 

    return render(request, 'order.html', {'form': form})

    # if request.method == 'POST':
    #     form =OrderForm(request.POST)
        
    #     if form.is_valid():
                        
    #         form.save()

    #         messages.error(request,'Order Confirmed') 
    #         form = OrderForm()
    #         context = { 'form' : form, 'order' :True } 
    #         return render(request,'order.html',context) 
    #     else:
    #         form =OrderForm(request.POST)
    #         context = { 'form' : form, 'order' :False } 
    #         messages.error(request,'OrderNot Confirmed') 
    #         return render(request,'order.html',context)

    # form =OrderForm()
    # context = { 'form' : form }
    # return render(request,'order.html',context)

# def person_update_view(request, pk):
#     person = get_object_or_404(Order, pk=pk)
#     form = OrderForm(instance=person)
#     if request.method == 'POST':
#         form = OrderForm(request.POST, instance=person)
#         if form.is_valid():
#             form.save()
#             return redirect('person_change', pk=pk)
#     return render(request, 'order.html', {'form': form})    


# AJAX
def load_course(request):
    department_id = request.GET.get('department_id')
    course = Course.objects.filter(department_id=department_id).all()
    # return render(request, 'city_dropdown_list.html', {'course': course})
    return JsonResponse(list(course.values('id', 'name')), safe=False)   

school/school_management/templates/add_product.html
<!DOCTYPE html>
<html>
    
    <head>
	<!-- <title>Login</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous"> -->

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    </head>
   
    <body>
        
        <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal" data-bs-whatever="@mdo">Add depaerment</button>
        <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal" data-bs-whatever="@fat">Add Course</button>
        <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal" data-bs-whatever="@getbootstrap">Add Materials</button>
        <p class="text-center text-muted mt-5 mb-0">Back to home? <a href="{% url 'admin_home' %}"
            class="fw-bold text-body"><u>click here</u></a></p>

        <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
          <div class="modal-dialog">
            <div class="modal-content">
              <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">New Details add</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
              </div>
              <div class="modal-body">
                <!-- <form>
                  <div class="mb-3">
                    <label for="recipient-name" class="col-form-label">Recipient:</label>
                    <input type="text" class="form-control" id="recipient-name">
                  </div>
                  <div class="mb-3">
                    <label for="message-text" class="col-form-label">Message:</label>
                    <textarea class="form-control" id="message-text"></textarea>
                  </div>
                </form> -->
                {%load crispy_forms_tags %} 
                     <form method="POST" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form|crispy }}
                        {% for message in messages %}  
                        <p>{{message}}</p>

                        {%endfor%}
                      <div class="form-outline mb-4">
                        <button class="btn btn-primary btn-lg btn-block" type="submit">submit</button>
                        <!-- <a href="{% url 'logout' %}"  button class="btn btn-primary btn-lg btn-block"></button>logout</a> -->
                      </div>
                      <!-- {%for message in messages%}
                       <p class='text-danger'>{{message}}</p>
                      {%endfor%}    -->
                      <!-- <div class="form-group">
                        <input type="submit" value="Login" class="btn float-right login_btn">
                      </div> -->
                     </form>
              </div>
              <!-- <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary">Send message</button>
              </div> -->
            </div>
          </div>
        </div>
    </body>
   </div>
    </html>

school/school_management/templates/admin_login.html
<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<!------ Include the above in your HEAD tag ---------->

<!DOCTYPE html><html lang='en' class=''>
<head><script src='//production-assets.codepen.io/assets/editor/live/console_runner-079c09a0e3b9ff743e39ee2d5637b9216b3545af0de366d4b9aad9dc87e26bfd.js'></script><script src='//production-assets.codepen.io/assets/editor/live/events_runner-73716630c22bbc8cff4bd0f07b135f00a0bdc5d14629260c3ec49e5606f98fdd.js'></script><script src='//production-assets.codepen.io/assets/editor/live/css_live_reload_init-2c0dc5167d60a5af3ee189d570b1835129687ea2a61bee3513dee3a50c115a77.js'></script><meta charset='UTF-8'><meta name="robots" content="noindex"><link rel="shortcut icon" type="image/x-icon" href="//production-assets.codepen.io/assets/favicon/favicon-8ea04875e70c4b0bb41da869e81236e54394d63638a1ef12fa558a4a835f1164.ico" /><link rel="mask-icon" type="" href="//production-assets.codepen.io/assets/favicon/logo-pin-f2d2b6d2c61838f7e76325261b7195c27224080bc099486ddd6dccb469b8e8e6.svg" color="#111" /><link rel="canonical" href="https://codepen.io/frytyler/pen/EGdtg" />

<link rel='stylesheet prefetch' href='https://cdnjs.cloudflare.com/ajax/libs/normalize/5.0.0/normalize.min.css'><script src='https://cdnjs.cloudflare.com/ajax/libs/prefixfree/1.0.7/prefixfree.min.js'></script>
<style class="cp-pen-styles">@import url(https://fonts.googleapis.com/css?family=Open+Sans);
.btn { display: inline-block; *display: inline; *zoom: 1; padding: 4px 10px 4px; margin-bottom: 0; font-size: 13px; line-height: 18px; color: #333333; text-align: center;text-shadow: 0 1px 1px rgba(255, 255, 255, 0.75); vertical-align: middle; background-color: #f5f5f5; background-image: -moz-linear-gradient(top, #ffffff, #e6e6e6); background-image: -ms-linear-gradient(top, #ffffff, #e6e6e6); background-image: -webkit-gradient(linear, 0 0, 0 100%, from(#ffffff), to(#e6e6e6)); background-image: -webkit-linear-gradient(top, #ffffff, #e6e6e6); background-image: -o-linear-gradient(top, #ffffff, #e6e6e6); background-image: linear-gradient(top, #ffffff, #e6e6e6); background-repeat: repeat-x; filter: progid:dximagetransform.microsoft.gradient(startColorstr=#ffffff, endColorstr=#e6e6e6, GradientType=0); border-color: #e6e6e6 #e6e6e6 #e6e6e6; border-color: rgba(0, 0, 0, 0.1) rgba(0, 0, 0, 0.1) rgba(0, 0, 0, 0.25); border: 1px solid #e6e6e6; -webkit-border-radius: 4px; -moz-border-radius: 4px; border-radius: 4px; -webkit-box-shadow: inset 0 1px 0 rgba(255, 255, 255, 0.2), 0 1px 2px rgba(0, 0, 0, 0.05); -moz-box-shadow: inset 0 1px 0 rgba(255, 255, 255, 0.2), 0 1px 2px rgba(0, 0, 0, 0.05); box-shadow: inset 0 1px 0 rgba(255, 255, 255, 0.2), 0 1px 2px rgba(0, 0, 0, 0.05); cursor: pointer; *margin-left: .3em; }
.btn:hover, .btn:active, .btn.active, .btn.disabled, .btn[disabled] { background-color: #e6e6e6; }
.btn-large { padding: 9px 14px; font-size: 15px; line-height: normal; -webkit-border-radius: 5px; -moz-border-radius: 5px; border-radius: 5px; }
.btn:hover { color: #333333; text-decoration: none; background-color: #e6e6e6; background-position: 0 -15px; -webkit-transition: background-position 0.1s linear; -moz-transition: background-position 0.1s linear; -ms-transition: background-position 0.1s linear; -o-transition: background-position 0.1s linear; transition: background-position 0.1s linear; }
.btn-primary, .btn-primary:hover { text-shadow: 0 -1px 0 rgba(0, 0, 0, 0.25); color: #ffffff; }
.btn-primary.active { color: rgba(255, 255, 255, 0.75); }
.btn-primary { background-color: #4a77d4; background-image: -moz-linear-gradient(top, #6eb6de, #4a77d4); background-image: -ms-linear-gradient(top, #6eb6de, #4a77d4); background-image: -webkit-gradient(linear, 0 0, 0 100%, from(#6eb6de), to(#4a77d4)); background-image: -webkit-linear-gradient(top, #6eb6de, #4a77d4); background-image: -o-linear-gradient(top, #6eb6de, #4a77d4); background-image: linear-gradient(top, #6eb6de, #4a77d4); background-repeat: repeat-x; filter: progid:dximagetransform.microsoft.gradient(startColorstr=#6eb6de, endColorstr=#4a77d4, GradientType=0);  border: 1px solid #3762bc; text-shadow: 1px 1px 1px rgba(0,0,0,0.4); box-shadow: inset 0 1px 0 rgba(255, 255, 255, 0.2), 0 1px 2px rgba(0, 0, 0, 0.5); }
.btn-primary:hover, .btn-primary:active, .btn-primary.active, .btn-primary.disabled, .btn-primary[disabled] { filter: none; background-color: #4a77d4; }
.btn-block { width: 100%; display:block; }

* { -webkit-box-sizing:border-box; -moz-box-sizing:border-box; -ms-box-sizing:border-box; -o-box-sizing:border-box; box-sizing:border-box; }

html { width: 100%; height:100%; overflow:hidden; }

body { 
	width: 100%;
	height:100%;
	font-family: 'Open Sans', sans-serif;
	background: #092756;
	background: -moz-radial-gradient(0% 100%, ellipse cover, rgba(104,128,138,.4) 10%,rgba(138,114,76,0) 40%),-moz-linear-gradient(top,  rgba(57,173,219,.25) 0%, rgba(42,60,87,.4) 100%), -moz-linear-gradient(-45deg,  #670d10 0%, #092756 100%);
	background: -webkit-radial-gradient(0% 100%, ellipse cover, rgba(104,128,138,.4) 10%,rgba(138,114,76,0) 40%), -webkit-linear-gradient(top,  rgba(57,173,219,.25) 0%,rgba(42,60,87,.4) 100%), -webkit-linear-gradient(-45deg,  #670d10 0%,#092756 100%);
	background: -o-radial-gradient(0% 100%, ellipse cover, rgba(104,128,138,.4) 10%,rgba(138,114,76,0) 40%), -o-linear-gradient(top,  rgba(57,173,219,.25) 0%,rgba(42,60,87,.4) 100%), -o-linear-gradient(-45deg,  #670d10 0%,#092756 100%);
	background: -ms-radial-gradient(0% 100%, ellipse cover, rgba(104,128,138,.4) 10%,rgba(138,114,76,0) 40%), -ms-linear-gradient(top,  rgba(57,173,219,.25) 0%,rgba(42,60,87,.4) 100%), -ms-linear-gradient(-45deg,  #670d10 0%,#092756 100%);
	background: -webkit-radial-gradient(0% 100%, ellipse cover, rgba(104,128,138,.4) 10%,rgba(138,114,76,0) 40%), linear-gradient(to bottom,  rgba(57,173,219,.25) 0%,rgba(42,60,87,.4) 100%), linear-gradient(135deg,  #670d10 0%,#092756 100%);
	filter: progid:DXImageTransform.Microsoft.gradient( startColorstr='#3E1D6D', endColorstr='#092756',GradientType=1 );
}
.login { 
	position: absolute;
	top: 50%;
	left: 50%;
	margin: -150px 0 0 -150px;
	width:300px;
	height:300px;
}
.login h1 { color: #fff; text-shadow: 0 0 10px rgba(0,0,0,0.3); letter-spacing:1px; text-align:center; }

input { 
	width: 100%; 
	margin-bottom: 10px; 
	background: rgba(0,0,0,0.3);
	border: none;
	outline: none;
	padding: 10px;
	font-size: 13px;
	color: #fff;
	text-shadow: 1px 1px 1px rgba(0,0,0,0.3);
	border: 1px solid rgba(0,0,0,0.3);
	border-radius: 4px;
	box-shadow: inset 0 -5px 45px rgba(100,100,100,0.2), 0 1px 1px rgba(255,255,255,0.2);
	-webkit-transition: box-shadow .5s ease;
	-moz-transition: box-shadow .5s ease;
	-o-transition: box-shadow .5s ease;
	-ms-transition: box-shadow .5s ease;
	transition: box-shadow .5s ease;
}
input:focus { box-shadow: inset 0 -5px 45px rgba(100,100,100,0.4), 0 1px 1px rgba(255,255,255,0.2); }
</style></head><body>
<div class="login">
	<h1>Admin Panel</h1>
    <form method="post" action="">
		{% csrf_token %}
    	<input type="text" name="email" placeholder="Email" required="required" />  
        <input type="password" name="password" placeholder="Password" required="required" />
        <button type="submit" class="btn btn-primary btn-block btn-large">Login</button>
    </form>
	{%for message in messages%}
        <p class='text-white'>{{message}}</p>
 
    {%endfor%}   
</div>
<script src='//production-assets.codepen.io/assets/common/stopExecutionOnTimeout-b2a7b3fe212eaa732349046d8416e00a9dec26eb7fd347590fbced3ab38af52e.js'></script>
<script >/* 

I built this login form to block the front end of most of my freelance wordpress projects during the development stage. 

This is just the HTML / CSS of it but it uses wordpress's login system. 

Nice and Simple

*/
//# sourceURL=pen.js
</script>
</body></html>

school/school_management/templates/city_dropdown.list.html
<option value="">---------</option>
{% for course in course %}
<option value="{{ course.pk }}">{{ course.name }}</option>
{% endfor %}

school/school_management/templates/login.html
<!DOCTYPE html>
 <html>
 <head>
   <title>Login Page</title>
    <!--Made with love by Mutiullah Samim -->
    
   <!--Bootsrap 4 CDN-->
   <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
     
     <!--Fontawesome CDN-->
   <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">
 
   <!--Custom styles-->
   <link rel="stylesheet" type="text/css" href="styles.css">
   <style>
    html,body{
      background-image: url('http://getwallpapers.com/wallpaper/full/a/5/d/544750.jpg');
      background-size: cover;
      background-repeat: no-repeat;
      height: 100%;
      font-family: 'Numans', sans-serif;
      }
      
      .container{
      height: 100%;
      align-content: center;
      }
      
      .card{
      height: 370px;
      margin-top: auto;
      margin-bottom: auto;
      width: 400px;
      background-color: rgba(0,0,0,0.5) !important;
      }
      
      .social_icon span{
      font-size: 60px;
      margin-left: 10px;
      color: #FFC312;
      }
      
      .social_icon span:hover{
      color: white;
      cursor: pointer;
      }
      
      .card-header h3{
      color: white;
      }
      
      .social_icon{
      position: absolute;
      right: 20px;
      top: -45px;
      }
      
      .input-group-prepend span{
      width: 50px;
      background-color: #FFC312;
      color: black;
      border:0 !important;
      }
      
      input:focus{
      outline: 0 0 0 0  !important;
      box-shadow: 0 0 0 0 !important;
      
      }
      
      .remember{
      color: white;
      }
      
      .remember input
      {
      width: 20px;
      height: 20px;
      margin-left: 15px;
      margin-right: 5px;
      }
      
      .login_btn{
      color: black;
      background-color: #FFC312;
      width: 100px;
      }
      
      .login_btn:hover{
      color: black;
      background-color: white;
      }
      
      .links{
      color: white;
      }
      
      .links a{
      margin-left: 4px;
      }



   </style>
 </head>
 <body>
 <div class="container">
   <div class="d-flex justify-content-center h-100">
     <div class="card">
       <div class="card-header">
         <h3>Sign In</h3>
         <div class="d-flex justify-content-end social_icon">
           <span><i class="fab fa-facebook-square"></i></span>
           <span><i class="fab fa-google-plus-square"></i></span>
           <span><i class="fab fa-twitter-square"></i></span>
         </div>
       </div>
       <div class="card-body">
         <form method="POST" action="">
           {% csrf_token %}
           <div class="input-group form-group">
             <div class="input-group-prepend">
               <span class="input-group-text"><i class="fas fa-user"></i></span>
             </div>
             <input type="text"  name="email" class="form-control" placeholder="email">
             
           </div>
           <div class="input-group form-group">
             <div class="input-group-prepend">
               <span class="input-group-text"><i class="fas fa-key"></i></span>
             </div>
             <input type="password" name="password" class="form-control" placeholder="password">
           </div>
           {%for message in messages%}
           <p class='text-danger'>{{message}}</p>
 
           {%endfor%}   
           <div class="row align-items-center remember">
             <input type="checkbox">Remember Me
           </div>
          
           <div class="form-group">
             <input type="submit" value="Login" class="btn float-right login_btn">
           </div>
         </form>
       </div>
       <div class="card-footer">
         <div class="d-flex justify-content-center links">
           Don't have an account?<a href="{% url 'signup' %}">Sign Up</a>
         </div>
         <div class="d-flex justify-content-center">
           <a href="#">Forgot your password?</a>
           
         </div>
       </div>
     </div>
   </div>
 </div>
 </body>
 </html>

school/school_management/templates/order.html
<!DOCTYPE html>
<html>
    
<head>
	<title>Login</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">


	 
    </head>
    <body>
        <section class="vh-100" style="background-color: #508bfc;">
            <div class="container py-5 h-100">
              <div class="row d-flex justify-content-center align-items-center h-100">
                <div class="col-12 col-md-8 col-lg-6 col-xl-5">
                  <div class="card shadow-2-strong" style="border-radius: 1rem;">
                    <div class="card-body p-5 text-center">
          
                      <h3 class="mb-5">purchase product</h3>
          
                      <!-- <div class="form-outline mb-4">
                        <input type="email" id="typeEmailX-2" class="form-control form-control-lg" />
                        <label class="form-label" for="typeEmailX-2">Email</label>
                      </div>  -->
                      {%load crispy_forms_tags %} 
                     <form method="POST" enctype="multipart/form-data" id='orderForm' data-course-url="{% url 'ajax_load_course' %}">
                        {% csrf_token %}
                        {{ form|crispy }}
                        
                      <div class="form-outline mb-4">
                        <button  class="btn btn-primary btn-lg btn-block" type="submit">submit</button>
                        <a href="{% url 'logout' %}"  button class="btn btn-primary btn-lg btn-block"></button>logout</a> 
                      </div>
                        <!-- {% if order %} 
                        <h1>hello</h1>
                        <div onload=" sweetalertclick()"></div>

                        {% endif %} -->
                      {% for message in messages %}
                       <p class='text-danger'>{{message}}</p>
                      {% endfor %}   
                      
                     </form>
          
                      <!-- Checkbox -->
                     <!-- <div class="form-check d-flex justify-content-start mb-4">
                        <input class="form-check-input" type="checkbox" value="" id="form1Example3" />
                        <label class="form-check-label" for="form1Example3"> Remember password </label>
                      </div> -->
          
                      
          
                      <!-- <hr class="my-4">
          
                      <button class="btn btn-lg btn-block btn-primary" style="background-color: #dd4b39;"
                        type="submit"><i class="fab fa-google me-2"></i> Sign in with google</button>
                      <button class="btn btn-lg btn-block btn-primary mb-2" style="background-color: #3b5998;"
                        type="submit"><i class="fab fa-facebook-f me-2"></i>Sign in with facebook</button>
          
                    </div>  -->
                  </div>
                </div>
              </div>
            </div>
          </section>
          <!-- <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
          <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
        <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
        <script>
          function sweetalertclick(){
            swal({
              title: "ORDER PLACED!",
              text: "THANK YOU,Keep shop with us",
              icon: "success",

              })
              setTimeout(()=>{
                
               window.location.href='http://127.0.0.1:8000/'
              },2000)
               
              
          }
        </script> -->
        <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<script>
    $("#id_department").change(function () {
        const url = $("#orderForm").attr("data-course-url");  // get the url of the `load_cities` view
        const departmentId = $(this).val();  // get the selected country ID from the HTML input

        $.ajax({                       // initialize an AJAX request
            url: url,                    // set the url of the request (= /persons/ajax/load-cities/ )
            data: {
                'department_id': departmentId       // add the country id to the GET parameters
            },
            success: function (data) {   // `data` is the return of the `load_cities` view function
                  //$("#id_course").html(data);  // replace the contents of the city input with the data that came from the server  
                

                let html_data = '<option value="">---------</option>';
                data.forEach(function (course) {
                    html_data += `<option value="${course.id}">${course.name}</option>`
                });
                console.log(html_data);
                $("#id_course").html(html_data);

                
            }
        });

    });
</script>
    </body>

    </html>